using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Services;

namespace CrackingWebService
{
    /// <summary>
    /// Summary description for CrackingWS
    /// </summary>
    [WebService(Namespace = "http://tempuri.org/")]
    [WebServiceBinding(ConformsTo = WsiProfiles.BasicProfile1_1)]
    [System.ComponentModel.ToolboxItem(false)]
    // To allow this Web CrackingWS to be called from script, using ASP.NET AJAX, uncomment the following line. 
    // [System.Web.Script.Services.ScriptService]
    public class CrackingWS : System.Web.Services.WebService
    {
        private SingletonCommon _sCommon;

        public SingletonCommon SCommon
        {
            get { return _sCommon; }
            set { _sCommon = value; }
        }

        [WebMethod]
        // Returns a list of strings, which contains a third of the dictionary.
        public List<string> GetDictionary()
        {
            // instancializes to the static object of the singleton.
            _sCommon = SingletonCommon.Instance;
            // Get list of string, based on which part is next to be given.
            List<string> returnList = _sCommon.MakeDictionaryParts(_sCommon.PartToGive);
            // increment, so next request for a dictionary part will be next part.
            _sCommon.PartToGive++;
            return returnList;

        }

        [WebMethod]
        public List<UserInfo> GetPasswords()
        {
            _sCommon = SingletonCommon.Instance;
            // Returns list of users / passwords from singleton.
            return (_sCommon.Passwords);

        }



        [WebMethod]
        // Default method autogenerated with soap .asmx item.
        public string HelloWorld()
        {
            // Hello World!! :) 
            return "Hello World!";
            // And Hello Henrik, Michael and Peter!
            //Regards from Ali, Janus, Martin and Paulina =)
        }
    }
}
